image: atjontv-docker-images.bintray.io/node:latest

stages:
- build
- deploy

cache:
  paths:
  - hydroedit/node_modules/
   
build:linux:
  stage: build
  script:
   - cd hydroedit/
   - npm install
   - npm run pkg-lin
   - cd ..
   - tar cvfz hydroedit-linux.tgz hydroedit/release-builds/hydroedit-linux-x64
  artifacts:
    paths:
      - hydroedit-linux.tgz
      
build:nt:
  stage: build
  script:
   - cd hydroedit/
   - npm install
   - npm run pkg-win
   - cd ..
   - tar cvfz hydroedit-win32.tgz hydroedit/release-builds/hydroedit-win32-ia32
  artifacts:
    paths:
      - hydroedit-win32.tgz
      
build:xnu:
  stage: build
  script:
   - cd hydroedit/
   - npm install
   - npm run pkg-mac
   - cd ..
   - tar cvfz hydroedit-darwin.tgz hydroedit/release-builds/hydroedit-darwin-x64
  artifacts:
    paths:
      - hydroedit-darwin.tgz
   
publish:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">.npmrc
    - npm publish